version: '3'

services:
# App Backend Service
  api:
    build: ./back-end
    ports:
      #expose port 3000 on the container to port 9191 on the host machine 
      - "9191:3000"
    #restart: always
    depends_on:
      - "db"
    networks:
      - backend
      - frontend

# App Frontend Service
  client:
    build: ./front-end
    ports:
      #expose port 5000 on the container to port 9090 on the host machine
      - "9090:5000"
    #restart: always
    depends_on:
      - "api"
    networks:
      - frontend

# Database Service (MySQL) 
  db:
    image: mysql:5.7
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3307'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'darkcastle'
      MYSQL_PASSWORD: 'darkcastle'
      MYSQL_ROOT_PASSWORD: 'root'
    # Where our data will be persisted
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

# Names our volume
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
